# Use the official Node.js 18 image as the base image
FROM node:20-alpine AS base

# Set the working directory in the container
WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm install

# Copy the rest of your app's code
COPY . .

# Expose port 3000 to the outside world
EXPOSE 3000

# Run the Next.js app
CMD ["npm", "run", "dev"]
